apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random
  template:
    metadata:
      labels:
        app: random
    spec:
      containers:
        - name: random
          image: adwera/ts-random-random 
          env:
            - name: MONGO_URI
              value: 'mongodb://random-mongo-service:27017/random'
            - name: NATS_CLUSTER_ID
              value: 'random'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URI
              value: 'http://nats-service:4222'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY 

---

apiVersion: v1
kind: Service
metadata:
  name: random-service
spec:
  selector:
    app: random
  ports:
    - name: random
      protocol: TCP
      port: 5002
      targetPort: 5002


